version: "3"

services:
  app:
    build: .
    # image: totomadne/game-server
    image: sha256:8b25f68eb8a9c5c3c98744faa4ea231f1f8a3bc89b359c67053d0d9025962501
    env_file: .env
    ports:
      - "${HOST_PORT}:80"
    depends_on:
      - database
    environment:
      - DATABASE_URL=${DATABASE_URL}
    command: /bin/bash docker.sh
    networks:
      - app-network

  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - database_data:/var/lib/mysql
    networks:
      - app-network

  mercure:
    image: dunglas/mercure
    restart: unless-stopped
    environment:
      SERVER_NAME: ":80"
      # MERCURE_SUBSCRIBER_JWT_ALG: "HS256"
      # MERCURE_PUBLISHER_JWT_ALG: "HS256"
      MERCURE_PUBLISHER_JWT_KEY: "!ChangeThisMercureHubJWTSecretKey!"
      MERCURE_SUBSCRIBER_JWT_KEY: "!ChangeThisMercureHubJWTSecretKey!"
      APP_SECRET: ${APP_SECRET}
      DATABASE_URL: ${DATABASE_URL}
      MERCURE_EXTRA_DIRECTIVES: |-
        cors_origins *
        publish_origins *
        demo
        ui
        anonymous
        subscriptions
      # Comment the following line to disable the development mode
      command: /usr/bin/caddy run --config /etc/caddy/Caddyfile.dev
    ports:
      - "${MERCURE_PORT}:80"
    volumes:
      - mercure_data:/data
      - mercure_config:/config
    networks:
      - app-network

###< symfony/mercure-bundle ###

networks:
  app-network:
    driver: bridge

volumes:
  ###> doctrine/doctrine-bundle ###
  database_data:
  ###< doctrine/doctrine-bundle ###

  ###> symfony/mercure-bundle ###
  mercure_data:
  mercure_config:
###< symfony/mercure-bundle ###
