version: "3"

services:
  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: scoobyflag
      MYSQL_USER: scoobyflag
      MYSQL_PASSWORD: scoobyflag
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql

  app:
    image: b6eb153c04c6b4d827789039fd0c9d3e09b349282395bca17910c6470fdeacda
    ports:
      - "1650:80"
    depends_on:
      - database
    environment:
      - DATABASE_URL: "mysql://scoobyflag:scoobyflag@database:3306/${DB_NAME}"
